/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#fefcff",
        "surface-container-low": "#f2f4f7",
        "surface-variant": "#e0e3e6",
        "tertiary-container": "#9d6a00",
        "primary-fixed": "#d9e2ff",
        "error": "#ba1a1a",
        "on-surface-variant": "#414755",
        "surface-bright": "#f7f9fc",
        "outline": "#727786",
        "surface-container-highest": "#e0e3e6",
        "on-tertiary-fixed-variant": "#614000",
        "tertiary-fixed": "#ffddb0",
        "surface-container": "#eceef1",
        "on-secondary-fixed-variant": "#1a5200",
        "on-error": "#ffffff",
        "surface-dim": "#d8dadd",
        "secondary": "#266d00",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8eb",
        "tertiary-fixed-dim": "#ffba45",
        "on-primary-fixed": "#001a43",
        "on-secondary-fixed": "#062100",
        "surface-tint": "#0059c7",
        "secondary-fixed-dim": "#6de039",
        "on-primary-fixed-variant": "#004398",
        "on-secondary-container": "#287100",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#281800",
        "on-tertiary-container": "#fffbff",
        "on-surface": "#191c1e",
        "inverse-on-surface": "#eff1f4",
        "primary-fixed-dim": "#afc6ff",
        "outline-variant": "#c1c6d7",
        "surface": "#f7f9fc",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "primary": "#0057c2",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-container": "#006ef2",
        "tertiary": "#7d5400",
        "background": "#f7f9fc",
        "secondary-container": "#85fa51",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#afc6ff"
      },
      spacing: {
        "unit": "8px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "container-margin": "24px",
        "gutter": "16px"
      }
    },
  },
  plugins: [],
}